export const NOTIF_TYPE = {
  AppUser_DigitalNotification: 101,
  AppUser_Vote: 102,
  AppUser_CitizenFeedback: 103,
  AppUser_Invoice: 104,
  AppUser_DigitalService: 105,
  AppUser_LocalAmenities: 106,
  AppUser_Administrative: 107,
  AppUser_QnA: 108,
  AppUser_Hotline: 109,
  AppUser_Social_Shopping: 110,
  AppUser_Social_Booking: 111,
  AppUser_Social_Map: 112,
  AppUser_Social_FlashSale: 113,
  AppUser_Social_Voucher: 114,
  AppUser_Social_TopProvider: 115,
  AppUser_Social_TopProduct: 116,
  AppUser_Social_TopService: 117,
  AppUser_Social_Education: 118,
  AppUser_Social_Cuisine: 119,
  AppUser_Social_Medical: 120,
  AppUser_Social_HealthCare: 121,
  AppUser_Social_Travel: 122,
  AppUser_Social_Stay: 123,
  AppUser_Social_Village: 124,
  AppUser_Social_Entertainment: 125,
  AppUser_Social_Repair: 126,
  AppUser_Social_Job: 127,
  AppUser_Social_Traffic: 128,
  AppUser_Social_Sport: 129,
  AppSeller_ShopInfo: 201,
  AppSeller_ProductInfo: 202,
  AppSeller_Amenities: 203,
  AppSeller_Voucher: 204,
  AppSeller_Promotion: 205,
  AppSeller_Ads: 206,
  AppSeller_FlashSale: 207,
};

export const NOTIF_TYPE_NAME = {
  AppUser_DigitalNotification: 'AppUser_DigitalNotification',
  AppUser_Vote: 'AppUser_Vote',
  AppUser_CitizenFeedback: 'AppUser_CitizenFeedback',
  AppUser_Invoice: 'AppUser_Invoice',
  AppUser_DigitalService: 'AppUser_DigitalService',
  AppUser_LocalAmenities: 'AppUser_LocalAmenities',
  AppUser_Administrative: 'AppUser_Administrative',
  AppUser_QnA: 'AppUser_QnA',
  AppUser_Hotline: 'AppUser_Hotline',
  AppUser_Social_Shopping: 'AppUser_Social_Shopping',
  AppUser_Social_Booking: 'AppUser_Social_Booking',
  AppUser_Social_Map: 'AppUser_Social_Map',
  AppUser_Social_FlashSale: 'AppUser_Social_FlashSale',
  AppUser_Social_Voucher: 'AppUser_Social_Voucher',
  AppUser_Social_TopProvider: 'AppUser_Social_TopProvider',
  AppUser_Social_TopProduct: 'AppUser_Social_TopProduct',
  AppUser_Social_TopService: 'AppUser_Social_TopService',
  AppUser_Social_Education: 'AppUser_Social_Education',
  AppUser_Social_Cuisine: 'AppUser_Social_Cuisine',
  AppUser_Social_Medical: 'AppUser_Social_Medical',
  AppUser_Social_HealthCare: 'AppUser_Social_HealthCare',
  AppUser_Social_Travel: 'AppUser_Social_Travel',
  AppUser_Social_Stay: 'AppUser_Social_Stay',
  AppUser_Social_Village: 'AppUser_Social_Village',
  AppUser_Social_Entertainment: 'AppUser_Social_Entertainment',
  AppUser_Social_Repair: 'AppUser_Social_Repair',
  AppUser_Social_Job: 'AppUser_Social_Job',
  AppUser_Social_Traffic: 'AppUser_Social_Traffic',
  AppUser_Social_Sport: 'AppUser_Social_Sport',
  AppSeller_ShopInfo: 'AppSeller_ShopInfo',
  AppSeller_ProductInfo: 'AppSeller_ProductInfo',
  AppSeller_Amenities: 'AppSeller_Amenities',
  AppSeller_Voucher: 'AppSeller_Voucher',
  AppSeller_Promotion: 'AppSeller_Promotion',
  AppSeller_Ads: 'AppSeller_Ads',
  AppSeller_FlashSale: 'AppSeller_FlashSale',
};

export const NOTIF_TYPES_ARRAY = [
  { label: 'AppUser_DigitalNotification', value: 101 },
  { label: 'AppUser_Vote', value: 102 },
  { label: 'AppUser_CitizenFeedback', value: 103 },
  { label: 'AppUser_Invoice', value: 104 },
  { label: 'AppUser_DigitalService', value: 105 },
  { label: 'AppUser_LocalAmenities', value: 106 },
  { label: 'AppUser_Administrative', value: 107 },
  { label: 'AppUser_QnA', value: 108 },
  { label: 'AppUser_Hotline', value: 109 },
  { label: 'AppUser_Social_Shopping', value: 110 },
  { label: 'AppUser_Social_Booking', value: 111 },
  { label: 'AppUser_Social_Map', value: 112 },
  { label: 'AppUser_Social_FlashSale', value: 113 },
  { label: 'AppUser_Social_Voucher', value: 114 },
  { label: 'AppUser_Social_TopProvider', value: 115 },
  { label: 'AppUser_Social_TopProduct', value: 116 },
  { label: 'AppUser_Social_TopService', value: 117 },
  { label: 'AppUser_Social_Education', value: 118 },
  { label: 'AppUser_Social_Cuisine', value: 119 },
  { label: 'AppUser_Social_Medical', value: 120 },
  { label: 'AppUser_Social_HealthCare', value: 121 },
  { label: 'AppUser_Social_Travel', value: 122 },
  { label: 'AppUser_Social_Stay', value: 123 },
  { label: 'AppUser_Social_Village', value: 124 },
  { label: 'AppUser_Social_Entertainment', value: 125 },
  { label: 'AppUser_Social_Repair', value: 126 },
  { label: 'AppUser_Social_Job', value: 127 },
  { label: 'AppUser_Social_Traffic', value: 128 },
  { label: 'AppUser_Social_Sport', value: 129 },
  { label: 'AppSeller_ShopInfo', value: 201 },
  { label: 'AppSeller_ProductInfo', value: 202 },
  { label: 'AppSeller_Amenities', value: 203 },
  { label: 'AppSeller_Voucher', value: 204 },
  { label: 'AppSeller_Promotion', value: 205 },
  { label: 'AppSeller_Ads', value: 206 },
  { label: 'AppSeller_FlashSale', value: 207 },
];
