export const PERMISSION_ERP = {
  ERP_Admin: 'ERP.Admin',
  ERP_Admin_SystemConfig: 'ERP.Admin.SystemConfig',
  ERP_Admin_SystemConfig_Account: 'ERP.Admin.SystemConfig.Account',
  ERP_Admin_SystemConfig_Role: 'ERP.Admin.SystemConfig.Role',
  ERP_Admin_SystemConfig_ShopList: 'ERP.Admin.SystemConfig.ShopList',
  ERP_Admin_SystemConfig_Contract: 'ERP.Admin.SystemConfig.Contract',
  ERP_Admin_SystemConfig_Branch: 'ERP.Admin.SystemConfig.Branch',
  ERP_Admin_SystemConfig_Staff: 'ERP.Admin.SystemConfig.Staff',
  ERP_Admin_SystemConfig_ServicePackage:
    'ERP.Admin.SystemConfig.ServicePackage',
  ERP_Admin_SystemConfig_Tax: 'ERP.Admin.SystemConfig.Tax',
  ERP_Admin_SystemConfig_Pricing: 'ERP.Admin.SystemConfig.Pricing',
  ERP_Admin_Product: 'ERP.Admin.Product',
  ERP_Admin_Product_View: 'ERP.Admin.Product.View',
  ERP_Admin_Product_Create: 'ERP.Admin.Product.Create',
  ERP_Admin_Product_Update: 'ERP.Admin.Product.Update',
  ERP_Admin_Product_Delete: 'ERP.Admin.Product.Delete',
  ERP_Admin_Product_Export: 'ERP.Admin.Product.Export',
  ERP_Admin_Product_Import: 'ERP.Admin.Product.Import',
  ERP_Admin_Customer: 'ERP.Admin.Customer',
  ERP_Admin_Customer_View: 'ERP.Admin.Customer.View',
  ERP_Admin_Customer_ViewAll: 'ERP.Admin.Customer.ViewAll',
  ERP_Admin_Customer_Create: 'ERP.Admin.Customer.Create',
  ERP_Admin_Customer_Update: 'ERP.Admin.Customer.Update',
  ERP_Admin_Customer_Delete: 'ERP.Admin.Customer.Delete',
  ERP_Admin_Customer_Export: 'ERP.Admin.Customer.Export',
  ERP_Admin_Customer_Import: 'ERP.Admin.Customer.Import',
  ERP_Admin_Order: 'ERP.Admin.Order',
  ERP_Admin_Order_View: 'ERP.Admin.Order.View',
  ERP_Admin_Order_ViewAll: 'ERP.Admin.Order.ViewAll',
  ERP_Admin_Order_Create: 'ERP.Admin.Order.Create',
  ERP_Admin_Order_Update: 'ERP.Admin.Order.Update',
  ERP_Admin_Order_Verify: 'ERP.Admin.Order.Verify',
  ERP_Admin_Order_Cancel: 'ERP.Admin.Order.Cancel',
  ERP_Admin_Order_Export: 'ERP.Admin.Order.Export',
  ERP_Admin_Order_Import: 'ERP.Admin.Order.Import',
  ERP_Admin_Order_Packaging: 'ERP.Admin.Order.Packaging',
  ERP_Admin_Order_Payment: 'ERP.Admin.Order.Payment',
  ERP_Admin_Delivery: 'ERP.Admin.Delivery',
  ERP_Admin_Loyalty: 'ERP.Admin.Loyalty',
  ERP_Admin_Marketing: 'ERP.Admin.Marketing',
  ERP_Admin_Report: 'ERP.Admin.Report',
  ERP_Admin_Offline: 'ERP.Admin.Offline',
  ERP_Admin_Website: 'ERP.Admin.Website',
  ERP_Admin_Guarantee: 'ERP.Admin.Guarantee',
  ERP_Admin_CashBook: 'ERP.Admin.CashBook',
  ERP_Admin_General: 'ERP.Admin.General',
  ERP_Admin_SocialChanel: 'ERP.Admin.SocialChanel',
  ERP_Admin_Application: 'ERP.Admin.Application',
};

export const PERMISSION_ERP_VI = {
  'ERP.Admin': 'Quản trị hệ thống ERP',
  'ERP.Admin.SystemConfig': 'Cấu hình hệ thống',
  'ERP.Admin.SystemConfig.Account': 'Quản lý tài khoản',
  'ERP.Admin.SystemConfig.Role': 'Quản lý phân quyền',
  'ERP.Admin.SystemConfig.ShopList': 'Quản lý cửa hàng',
  'ERP.Admin.SystemConfig.Contract': 'Quản lý hợp đồng',
  'ERP.Admin.SystemConfig.Branch': 'Quản lý chi nhánh',
  'ERP.Admin.SystemConfig.Staff': 'Quản lý nhân viên',
  'ERP.Admin.SystemConfig.ServicePackage': 'Quản lý gói dịch vụ',
  'ERP.Admin.SystemConfig.Tax': 'Cấu hình thuế',
  'ERP.Admin.SystemConfig.Pricing': 'Cấu hình chính sách giá',
  'ERP.Admin.Product': 'Quản lý sản phẩm',
  'ERP.Admin.Product.View': 'Xem sản phẩm',
  'ERP.Admin.Product.Create': 'Tạo sản phẩm',
  'ERP.Admin.Product.Update': 'Sửa sản phẩm',
  'ERP.Admin.Product.Delete': 'Xóa',
  'ERP.Admin.Product.Export': 'Xuất file sản phẩm',
  'ERP.Admin.Product.Import': 'Nhập file sản phẩm',
  'ERP.Admin.Customer': 'Khách hàng',
  'ERP.Admin.Customer.View': 'Xem khách hàng được phụ trách',
  'ERP.Admin.Customer.ViewAll': 'Xem tất cả khách hàng',
  'ERP.Admin.Customer.Create': 'Thêm khách hàng',
  'ERP.Admin.Customer.Update': 'Sửa khách hàng',
  'ERP.Admin.Customer.Delete': 'Xóa khách hàng',
  'ERP.Admin.Customer.Export': 'Xuất file khách hàng',
  'ERP.Admin.Customer.Import': 'Nhập file khách hàng',
  'ERP.Admin.Order': 'Đơn hàng',
  'ERP.Admin.Order.View': 'Xem đơn hàng được phụ trách',
  'ERP.Admin.Order.ViewAll': 'Xem tất cả đơn hàng',
  'ERP.Admin.Order.Create': 'Tạo đơn hàng',
  'ERP.Admin.Order.Update': 'Sửa đơn hàng',
  'ERP.Admin.Order.Verify': 'Duyệt đơn hàng',
  'ERP.Admin.Order.Cancel': 'Hủy đơn hàng',
  'ERP.Admin.Order.Export': 'Xuất file đơn hàng',
  'ERP.Admin.Order.Import': 'Nhập file đơn hàng ',
  'ERP.Admin.Order.Packaging': 'Đóng gói và giao hàng',
  'ERP.Admin.Order.Payment': 'Thanh toán đơn hàng',
  'ERP.Admin.Delivery': 'Vận chuyển',
  'ERP.Admin.Loyalty': 'Loyalty',
  'ERP.Admin.Marketing': 'Marketing',
  'ERP.Admin.Report': 'Báo cáo',
  'ERP.Admin.Offline': 'Bán hàng tại quầy',
  'ERP.Admin.Website': 'Website',
  'ERP.Admin.Guarantee': 'Bảo hàng',
  'ERP.Admin.CashBook': 'Sổ quỹ',
  'ERP.Admin.General': 'Tổng quan',
  'ERP.Admin.SocialChanel': 'Kênh social',
  'ERP.Admin.Application': 'Ứng dụng',
};
